### ISSUE TITLE
Proto files for 7.0.2 and 7.1.1?

### ISSUE THREAD

**Issue by tedpelas** [ios-xr/model-driven-telemetry#13]
Any news on when the proto files for XR 7.0.2 and 7.1.1 will be released?

Thank you

**Comment by satyacube** [comment]
#14

**Comment by tedpelas** [comment]
Is there a guide or similar on how to create these proto files on our own?

**Comment by satyacube** [comment]
There isn't a guide for IOS-XR users available yet. However, this item is in our roadmap.
