### ISSUE TITLE
Looking for latest IOS-XR protobuf definitions

### ISSUE THREAD

**Issue by spiderweb62** [ios-xr/model-driven-telemetry#18]
I am waiting on the lates versions definition (specifically IOS-XR 7.4.2 for ASR9K's). Any ETA on when this will be available?

Thanks a lot for your help

Andreas

**Comment by satyacube** [comment]
Hello! The protos will be uploaded once IOS-XR 7.4.2 is available for download.

**Comment by spiderweb62** [comment]
Hi there, apparently 7.4.2 is now available, would you be able to provide an ETA on when it will be pushed to the repo?

thanks a lot

Regards

Andreas

**Comment by satyacube** [comment]
Hello!
Just updated the repo with the protos.

Regards,
Satya

**Comment by spiderweb62** [comment]
Thank. you so much, I guess I can close this now :-)
