### ISSUE TITLE
Missing encoding path 

### ISSUE THREAD

**Issue by spiderweb62** [ios-xr/model-driven-telemetry#19]
Hi there,

I noticed one missing path from 721

Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-NCS-BDplatforms-npu-resources-oper:hw-resources-datas/hw-resources-data/npu-hwr/bank

But the yang model exists:

https://github.com/YangModels/yang/blob/main/vendor/cisco/xr/721/Cisco-IOS-XR-platforms-ofa-oper.yang

Would you kindly be able to add this proto definition please

Thanks a lot

Regards

Andreas Weber

**Comment by satyacube** [comment]
Hello! Let me check why the protos for that model were not generated.
Regards,
-Satya

**Comment by spiderweb62** [comment]
Hi there, was there any update to this please
