### ISSUE TITLE
Missing path proto definition on 7.7.2

### ISSUE THREAD

**Issue by spiderweb62** [ios-xr/model-driven-telemetry#22]
Hi there, the following path is missing from the 7.7.2 protobuf definitions:
Cisco-IOS-XR-asr9k-np-oper:hardware-module-np/nodes/node/nps/np/counters

By checking the Yang definitions, I can see this is existing:
https://github.com/YangModels/yang/blob/main/vendor/cisco/xr/772/Cisco-IOS-XR-asr9k-np-oper.yang

Thanks for looking into this

Regards

Andreas

**Comment by satyacube** [comment]
Hello!
I have added them to the repo.
Regards,
-Satya

**Comment by spiderweb62** [comment]
The protobuf files have been update, but not cisco_ios_xr_yang2proto_map.json. Can you also update that please
