### ISSUE TITLE
More paths missing on 7.7.2

### ISSUE THREAD

**Issue by spiderweb62** [ios-xr/model-driven-telemetry#23]
I noticed a few more paths missing on IOS XR 7.7.2:
Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/producer/statistics
Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter
Cisco-IOS-XR-envmon-oper:power-management/rack/consumers/consumer-nodes/consumer-node
Cisco-IOS-XR-envmon-oper:power-management/rack/producers/producer-nodes/producer-node

But also https://github.com/ios-xr/model-driven-telemetry/issues/22 was closed, however the cisco_ios_xr_yang2proto_map.json was not updated with the new paths

Kind regards

Andreas

**Comment by satyacube** [comment]
Andreas,
I have uploaded the missing protos and also updated the mapping file. Let me know if you have additional questions.
